version: 2.1

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6

commands:
  setup_bundle:
    steps:
      - restore_cache:
          key: bundle-{{ checksum "tracecontroller.gemspec" }}
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "tracecontroller.gemspec" }}
          paths:
          - vendor/bundle

jobs:
  test:
    executor: default
    steps:
      - checkout
      - setup_bundle
      - run: bundle exec rspec ./spec

workflows:
  version: 2

  test:
    jobs:
      - test
